### ISSUE TITLE
.net core 5 has an arm x64 binary

### ISSUE THREAD

**Issue by voronoipotato** [dstaley/is-windows-on-arm-ready#1]
https://dotnet.microsoft.com/download/dotnet/5.0?utm_source=dotnet-website&utm_medium=banner&utm_campaign=preview5-banner

They plan on also having an installer. I'm not sure if this counts for anything yet but perhaps this can be a placeholder for when it does.

**Comment by MikeChou** [comment]
.NET 5.0 RC2 release already includes the installer for Windows ARM64.
https://dotnet.microsoft.com/download/dotnet/5.0

**Comment by dstaley** [comment]
Fixed by 8fd183072367d3dac09a866a68d37f9ffb01d6ec
