### ISSUE TITLE
Qt is ready for Windows ARM64

### ISSUE THREAD

**Issue by tommyvct** [dstaley/is-windows-on-arm-ready#10]
Also for [OBS Studio](https://github.com/tommyvct/obs-studio).

**Comment by tommyvct** [comment]
FFmepg is doable, too.

**Comment by tommyvct** [comment]
Git is a work in progress.

**Comment by dstaley** [comment]
We only track officially released versions. As far as I can tell, Qt, OBS, FFmpeg, and Git do not have officially released ARM64 versions.
