### ISSUE TITLE
Microsoft To Do and Your Phone

### ISSUE THREAD

**Issue by alibabahck** [dstaley/is-windows-on-arm-ready#11]
Microsoft To-do is actually compiled for arm and also although Your Phone once was compiled for arm64 it is no longer. I haven't really used GitHub so I don't know how to formally propose changes.

Also Sysinternals has been ported to Arm64

Adobe Creative Cloud is available for arm64 so is Lightroom, Photoshop is available but only as a beta version.

**Comment by dstaley** [comment]
Thanks for the report!

We only track ARM64 versions, so Your Phone doesn't qualify. We also only track stable, released versions, so once Photoshop and Lightroom for ARM64 come out of beta we can update those.
