### ISSUE TITLE
Adobe Photoshop has released a (Beta) version compiled for ARM.

### ISSUE THREAD

**Issue by KritantaDev** [dstaley/is-windows-on-arm-ready#13]
https://feedback.photoshop.com/conversations/photoshop-beta/photoshop-beta-for-windows-arm-is-here/5fb3584b38150f55db64b1e4

Using https://devblogs.microsoft.com/directx/announcing-the-opencl-and-opengl-compatibility-pack-for-windows-10-on-arm/, native GPU acceleration is provided.

Been using this since December; all functionality is present and working, haven't had a single crash, should IMO be considered ready.

when you access the Adobe CC App Installer from an ARM PC it's presented directly to you, on the main screen, as the only thing you can install. Adobe and Windows both have been promoting it often.

**Comment by dstaley** [comment]
Fixed by #14
