### ISSUE TITLE
OpenJDK

### ISSUE THREAD

**Issue by dstaley** [dstaley/is-windows-on-arm-ready#5]
https://github.com/microsoft/openjdk-aarch64

**Comment by soapdog** [comment]
this just happened: https://devblogs.microsoft.com/java/announcing-openjdk-windows-arm/

**Comment by dstaley** [comment]
Yup, that's where I saw the announcement! That's why I opened this issue to keep an eye on it for the final stable release.

**Comment by cxnder** [comment]
Appears to be completed:

Downloads listed with the rest on their official page:
https://docs.microsoft.com/en-us/java/openjdk/download
