### ISSUE TITLE
Make VSCode Green

### ISSUE THREAD

**Issue by Stammark** [dstaley/is-windows-on-arm-ready#6]
ARM64 Native VSCode recently became a thing after https://github.com/microsoft/vscode/issues/33620#issuecomment-635367046

I think that is the same as what you get if you go to https://code.visualstudio.com/#alt-downloads and choose the ARM download (i.e. it's ARM64, not "ARM"==32-bit-armv7), but I don't have a native machine to test this on rn

**Comment by dstaley** [comment]
Thanks for the heads up! I've merged our open PR.
